// Automatically generated by astro-icon
// 3cac6b2c8146ed487df98b6ae89d7ca4f741507ca194569973090bb23434a498

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-right"
		| "arrow-up"
		| "code"
		| "envelope"
		| "eye"
		| "file"
		| "github"
		| "linkedin";
}